CXX = g++
OPTIMIZATION_DEBUG = -O3 -g
OPTIONS			 = -std=c++0x

LDLIBS			 = -O3 
COMPILER_OPTIONS =
COMPILER_OPTIONS += $(OPTIONS)
COMPILER_OPTIONS += $(OPTIMIZATION_DEBUG)


LINKER_OPTIONS =  $(LDLIBS)


###############################################################################

.PHONY: all

all: ng-count 


###############################################################################

ONAMES_NGCOUNT	= 	count\
			anyoption

mk_OFILES    = $(addsuffix .o,$(1))

OFILES_NGCOUNT	     = $(call mk_OFILES,$(ONAMES_NGCOUNT))



ng-count: Makefile $(OFILES_NGCOUNT)
	${CXX} $(OFILES_NGCOUNT) -o $@ ${LINKER_OPTIONS} 
	
%.o: %.cpp Makefile
	${CXX} -c -o $@ $< ${COMPILER_OPTIONS}

%.omp.o: %.cpp Makefile
	${CXX} -c -o $@ $< ${COMPILER_OPTIONS} ${OMP_OPT} 
###############################################################################

.PHONY: clean

RM = rm -f

DEP = makefile.dep

clean:
	$(RM) $(DEP)
	$(RM) *.o

distclean: clean
	$(RM) wng-count wng-pen-count
###############################################################################

FILES = $(wildcard *.cpp)

$(DEP): Makefile
	echo "Creating makefile.dep"
	echo '# DO NOT EDIT THIS FILE -- it is automatically generated' > $@
	echo '' >> $@

	for file in $(FILES); \
	do \
		${CXX} -MM -c $$file ${COMPILER_OPTIONS}; \
		echo ' '; \
	done | \
	awk 'BEGIN {RS=" "} (! /^\//) {if($$0!="\\\n"){\
	        if($$0 ~ /:/) {\
	                sub(/\n/,"",$$0);\
		        printf "\n%s \\\n", $$0\
	        } else {\
	                if($$0 ~ /\n/){\
	                        print "",$$0\
	                } else {\
	                        print "",$$0,"\\"\
	                }\
	        }\
	}}' - >> $@

-include $(DEP)

###############################################################################

HEADERS  = $(wildcard *.h)

%.hct.cpp:
	echo '#include "$*.h"' > $@

header-compile-test: $(HEADERS:.h=.hct.o)

header-compile-test-clean:
	$(RM) *.hct.*
